export const LOGIN_START = "login_start"
export const LOGIN_SUCCESS = "login_success"
export const LOGIN_FAIL ="login_fail"
export const LOGOUT_USER="logout_user"
export const CLEAR_ERRORS ="clear_errors"